$(document).ready(function(){
		$(".professor1").addClass("zoom").addClass("imagembordaClara");
		$(".professor2").removeClass("zoom");
		$(".professor3").removeClass("zoom");
		$(".professor4").removeClass("zoom");
		$(".professor5").removeClass("zoom");
		$(".professor6").removeClass("zoom");
		$(".professor7").removeClass("zoom");
		//
		$(".abrirProfessor1").fadeIn();
		$(".abrirProfessor2").hide();
		$(".abrirProfessor3").hide();
		$(".abrirProfessor4").hide();
		$(".abrirProfessor5").hide();
		$(".abrirProfessor6").hide();
		$(".abrirProfessor7").hide();
				
		$(".professor1").click(function(){
			$(".professor1").addClass("zoom").addClass("imagembordaClara");
			$(".professor2").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor3").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor4").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor5").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor6").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor7").removeClass("zoom").removeClass("imagembordaClara");
			//
			$(".abrirProfessor1").fadeIn();
			$(".abrirProfessor2").hide();
			$(".abrirProfessor3").hide();
			$(".abrirProfessor4").hide();
			$(".abrirProfessor5").hide();
			$(".abrirProfessor6").hide();
			$(".abrirProfessor7").hide();
		});
			
		$(".professor2").click(function(){
			$(".professor1").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor2").addClass("zoom").addClass("imagembordaClara");
			$(".professor3").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor4").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor5").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor6").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor7").removeClass("zoom").removeClass("imagembordaClara");
			//
			$(".abrirProfessor1").hide();
			$(".abrirProfessor2").fadeIn();
			$(".abrirProfessor3").hide();
			$(".abrirProfessor4").hide();
			$(".abrirProfessor5").hide();
			$(".abrirProfessor6").hide();
			$(".abrirProfessor7").hide();
		});
			
		$(".professor3").click(function(){
			$(".professor1").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor2").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor3").addClass("zoom").addClass("imagembordaClara");
			$(".professor4").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor5").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor6").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor7").removeClass("zoom").removeClass("imagembordaClara");
			//
			$(".abrirProfessor1").hide();
			$(".abrirProfessor2").hide();
			$(".abrirProfessor3").fadeIn();
			$(".abrirProfessor4").hide();
			$(".abrirProfessor5").hide();
			$(".abrirProfessor6").hide();
			$(".abrirProfessor7").hide();
		});
		
		$(".professor4").click(function(){
			$(".professor1").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor2").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor3").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor4").addClass("zoom").addClass("imagembordaClara");
			$(".professor5").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor6").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor7").removeClass("zoom").removeClass("imagembordaClara");
			//
			$(".abrirProfessor1").hide();
			$(".abrirProfessor2").hide();
			$(".abrirProfessor3").hide();
			$(".abrirProfessor4").fadeIn();
			$(".abrirProfessor5").hide();
			$(".abrirProfessor6").hide();
			$(".abrirProfessor7").hide();
		});
		
		$(".professor5").click(function(){
			$(".professor1").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor2").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor3").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor4").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor5").addClass("zoom").addClass("imagembordaClara");
			$(".professor6").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor7").removeClass("zoom").removeClass("imagembordaClara");
			//
			$(".abrirProfessor1").hide();
			$(".abrirProfessor2").hide();
			$(".abrirProfessor3").hide();
			$(".abrirProfessor4").hide();
			$(".abrirProfessor5").fadeIn();
			$(".abrirProfessor6").hide();
			$(".abrirProfessor7").hide();
		});
		
		$(".professor6").click(function(){
			$(".professor1").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor2").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor3").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor4").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor5").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor6").addClass("zoom").addClass("imagembordaClara");
			$(".professor7").removeClass("zoom").removeClass("imagembordaClara");
			//
			$(".abrirProfessor1").hide();
			$(".abrirProfessor2").hide();
			$(".abrirProfessor3").hide();
			$(".abrirProfessor4").hide();
			$(".abrirProfessor5").hide();
			$(".abrirProfessor6").fadeIn();
			$(".abrirProfessor7").hide();
		});
		
		$(".professor7").click(function(){
			$(".professor1").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor2").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor3").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor4").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor5").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor6").removeClass("zoom").removeClass("imagembordaClara");
			$(".professor7").addClass("zoom").addClass("imagembordaClara");
			//
			$(".abrirProfessor1").hide();
			$(".abrirProfessor2").hide();
			$(".abrirProfessor3").hide();
			$(".abrirProfessor4").hide();
			$(".abrirProfessor5").hide();
			$(".abrirProfessor6").hide();
			$(".abrirProfessor7").fadeIn();
		});
	}); 